name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      env:
          VSTEST_CONNECTION_TIMEOUT: 9000
    - name: Build
      run: dotnet build --no-restore
      env:
          VSTEST_CONNECTION_TIMEOUT: 9000
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
          VSTEST_CONNECTION_TIMEOUT: 9000
